apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  labels:
    app: wellness-front
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30002
  selector:
    app: wellness-front